[[CrosstoolNG]]
arch = "aarch64"
git-tree-sha1 = "d0e7e5c9b6c65ff721579efa5e07a1424fac48d7"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "011bc4f3a12f18f3fd81ffab04d7cd15f90c5db31529607536a1cf7508040efe"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.3-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-v1.25.3-aarch64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "aarch64"
git-tree-sha1 = "5a1bb45be40b1b399be4863afc3601c3264fdbf6"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "a8087dbb87011aac4f27f87c2fe27381ded7691f734db52b7999653aeac93df4"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.3-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-build_log-v1.25.3-aarch64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "aarch64"
git-tree-sha1 = "08e18f9bc6527bcc8a9f705a5df0c80531083a26"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "05590d720cdc475689db4ca7b937fea34a49ccadee85819e201367ebf4e6d4c1"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.3-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-extract_log-v1.25.3-aarch64-linux-gnu.tar.gz"
