[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "97467b29db0960c7698daba14c3e8054c67cfd76"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "5d894668ca6da1814e044844ef6b75a453734c28bc09f7b6b4c74e6b637c0878"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "bfb605bf2c5aa80e597a382fccff3d5c27eb85c4"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "42ba57ba1558b8ff510132a55d7d80e107e820ce72adb2bba2e88e27a82e18b7"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "393a65d2ff3b22355cb81d648cf84632eb448c96"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "6b3c52484e6ebcaa57a3205b5005c924ac93be8fa1ff41990221c2e83cc293ac"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
