[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "8bd8be23d41a99ec95070c3b21e0d6649859f84a"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "e9fae02371d8f5dff82f997fe906493fd5593f0238cbd29d3a0df898a0efc35a"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.0-GCCBoostrap-x86_64-linux-gnu/CrosstoolNG-v1.0.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "2fe7d2a07705f2213d81987a378edef2a306b487"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "9468fab971c278a99d7e955cff137bc07c691475cbf533569bea707593bffe69"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.0-GCCBoostrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.0.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "163a5961cd353e45656f4c7ce457fb3626b49d52"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "73904451909c38307be63b0ea313820710d1402fe84c6a8d64731add37502093"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.0-GCCBoostrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.0.0-x86_64-linux-gnu.tar.gz"
