[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "23eb818b99fa33809ca658de97f7d662653f90d0"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "1d5789f5d2bd87d68e46edb1eb1039c32333f97e039b04e0ab1e4110caf5c3f7"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "cf477718ea35e2d93ecb62ac1f169adeb956c7ed"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "57a1748ddda4c3ab27d69c878150f339ad29bc71a709336dada4b04578371e28"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "84d8fa73caca6431eeb4a8bcc2846247cf6644ce"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "7c4ecc51c2bb997f98bc9fd831344e88f14610ddd7538d8815280b1b99180d1a"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
