[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "605533a1a5ca044467032e27734501ae89dcc4e0"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "e8b6a6f457419a129a61414f512105ec1bf8adc3e8d443399abfe42cb3c1964f"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "1e830fa150600c91d2e086caef8feaaf32fa5a80"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "b1eef1dcb53a91e72bbc3f3397bd5e813e1c4524280fb4b148b167c885bc72c3"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "427d3c64d8d7ab4f7ab781caec0de5ee6d22f4fb"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "0d78ba7edf65f816486cb927faff13334c78b9696c713b0e0c720f86f94191b2"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
