[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "3dadef11b883a054feeddb9a707b0a6faca7500d"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "3027edfd34323a6e38654fb2baa499d3dbd13427d10a58316de5127ee4a5deee"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-v1.25.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "2c957c8889ec958dfbf20607a72c486ede0de776"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "c96aa2536caeaffb23e4056a4fa1649bce5b85a7070e7e8126e9ee3f34e0072d"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-build_log-v1.25.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "cf19b9400c54afe4196f14f25950cb9165e2943b"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "a2f7491b5d2015d1f7adb0a36f7fa4a5fd12ead24214da9f4ca70a6f29ff9b30"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-extract_log-v1.25.0-x86_64-linux-gnu.tar.gz"
