[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "1da07a834fb793870ef50c4ec34d38bfffb5044a"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "6167fd3a9bad53733a9b95ec0209d8cd2f57f5940f9ad4c955bbbb6add78f493"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "1c0485bcd856fa7612402c5e4cd4875d29351570"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "1ef94fcdb361162e4587ba6d3ece413622b825e5be402e9d2fd4ba1ac2694821"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f0aaa850e29059350357eedb6f4d445003f3b4a4"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "7e3979b70b233e6eaa7bc302b65f7e05278dbe79ddb4e57ed73a1c7d255482e2"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
