[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "b9e444dffdc6e3cab997ab8fd4cb4fce2f6786e1"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "392bce525dde0fc1b48a433b46d79bed13babdeda785773f8b24145a4dea31d5"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-v1.25.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "4374b308d2ae9e2d11e13763febba2a41ef8b920"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "1daff1740667865b28fdecfeb6bda3d84c4ebba69d8b2f0f2ca6574ebc68c239"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-build_log-v1.25.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "97720cd6bc80e41de2dc02d239283feaf86bafa6"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "3b612909e788d0929868f608fa4002e15d9c9644bfb03d4fd65b8d845b59d57b"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-extract_log-v1.25.0-x86_64-linux-gnu.tar.gz"
