[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "df194b543b492c51b50f8fd8304f58ef79ea03fc"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "2ca3a1c3c1e1e8127e7080c16cfa0a862f3c92cb34efeb00ccc7964d9a42d453"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "6b076c08672be2f0d5c1f5b6f23e7923ab23826d"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "68ca32b0c9d91bf315300df8ad4154de96af7cf79252367be98ae7167ab69c56"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "106e2152ef5de72ceeefe86cc4aa1be9589b5bdb"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "ee39db0a6af4249ae36258419f8dcd81a7da8f55047c7eb62aa43a98ed249a44"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
