[[CrosstoolNG]]
arch = "aarch64"
git-tree-sha1 = "403be1ea9b92b6846e0279902982ab04352bb8a7"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "3f08b0a9d11ec375c3d80d9e217540f63b94915dc6695d57e216e7127000f498"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-v1.25.0-aarch64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "aarch64"
git-tree-sha1 = "6afc9e34904f920817e4778d786a49c785a5620b"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "1b058c9ee5e6c5fc5c0f1a2e680c6c295ce6cda5eb93ed95650a250429ee87fb"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-build_log-v1.25.0-aarch64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "aarch64"
git-tree-sha1 = "74e4f82b3db14d261a0c8ad11184abe4f7520e50"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "60531b37e6dd53f63affc88e1b73fe82e2fdc4bc4eb0c5f4e330e3f0051b117e"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-extract_log-v1.25.0-aarch64-linux-gnu.tar.gz"
