[[CrosstoolNG]]
arch = "aarch64"
git-tree-sha1 = "60d01d35ed35989bb121bda9797d54ec936bbe9a"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "e7392cc4aae128ff90f448b260fadd95d172ff59ca21eb0d7d884a9692252971"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.4-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-v1.25.4-aarch64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "aarch64"
git-tree-sha1 = "ce7fef7051314239b4c2536368989bb01070d48f"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "337407b8e4de487a228dcd5643709ff8e1bf802d24e81a985dfbde694e5d4bd6"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.4-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-build_log-v1.25.4-aarch64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "aarch64"
git-tree-sha1 = "2011f1753f8cc48921623a2f2e952cec6744e7be"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "b69d55fdc925165ec452fd7ce6c3e81f230750964befeec7edcc0c7d8863caf0"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.4-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-extract_log-v1.25.4-aarch64-linux-gnu.tar.gz"
