[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "1165ecb9e6072625cbcbc58d27f6d6b0746d9f37"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "b2e06f84bb7d58abe7a26a817691ccabc263fef0e93cb509d47221c258654f8c"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.14-GCCBoostrap/CrosstoolNG-v1.0.14-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "fa6b2c599b43b61c00ea2e7316d1f40f08f51fb4"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "006732ba6d5205fe39555ccbba103907c947813b2484f8a5b278fe01f3581121"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.14-GCCBoostrap/CrosstoolNG-build_log-v1.0.14-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c1d9953288d380849c2f5f584b9b7966dd398f47"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "131b1f436dcc8410c85611b2a5f9abbda1cdce36024170d66eacf9a9ba60b2d0"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.14-GCCBoostrap/CrosstoolNG-extract_log-v1.0.14-x86_64-linux-gnu.tar.gz"
