[[CrosstoolNG]]
arch = "aarch64"
git-tree-sha1 = "a289ae9e47adfd660a398c3d84daf9ef3edc69b8"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "eecf910e729767632c7a78a7f2cfa8cd75a9cc73eb9e7193deffd8283e860c25"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.1-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-v1.25.1-aarch64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "aarch64"
git-tree-sha1 = "e2bcfe784e0b8312a054900ad56b9963ad149b9f"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "86ee580e388d0e42b723dd50fe158f53471d5e0a50e2410fb01a1db2274a3073"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.1-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-build_log-v1.25.1-aarch64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "aarch64"
git-tree-sha1 = "39b1d0f8beca9d882217a2dba9e7363b0c70a1c7"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "1e36e085d2eec5c7737177dc867fe7e90ac1657dfe2f325eff564b44d2a33fd7"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.1-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-extract_log-v1.25.1-aarch64-linux-gnu.tar.gz"
