[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "686984bcfcf6a4a2aa5612e40338c3e9f5627cdc"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "86cf3210d758926f57abed24f12f266e5cade71cf94ae1c8652ddf5f6296aef5"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "109a75d5c65b55c48595fe782369fe254aae898b"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "08a7fa97fef13af3937da03d38be9da695681593038c34ec8b945646cdedec03"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "64648f36a9c83008f9c7397794f6a6a575923206"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "06778a739d2b239cc439a3531829809eb337f5e2a20690bd7aa00f87e10fc689"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
