[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "294f3220adeb1389febf3b780bd80812aeca81fb"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "e6633297114292577d2dbdcc870882a04a641d52b952890ef1b189da970ef5b8"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-v1.25.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "ad0a0eefeb5aae519cc4d325569b95791f366209"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "ecbe9a7d9c3b3f2dc5bb33826d41d08737ae8c97668206c1e17749d4ca588acb"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-build_log-v1.25.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "264e1fbbf07636716878f8e4958d305607a54ebe"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "4d565e8ca67fd25245c770b48435001ddfe348e4e79fe7b2374ad43cfda5a82b"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-extract_log-v1.25.0-x86_64-linux-gnu.tar.gz"
