[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "25c29478ab54ebaa8be30420b55abe6597f4e26b"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "5ed2476478f75ba2a31da49a34194befd56274403ca934c23863df35817cf8b3"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "0edae446d6fdd04109ec3e931ab23fe0a96e49d0"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "010a886c9acdac540cedce5ce9c58b1110585a3ea0d499a19df72915e3980e05"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "813b1e4c61061c6efec7c6fe4bbdba32948b0fa3"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "ea5ff692b11f910270caff891ecb5149f2f8d7106dbb13067c6c96f430869db8"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
