[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "d4bf6fa761855817067fd1ff6d05dc1fc2849cc5"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "dffcac29ed02d2faf7f0f7c8bbccfc1164daab150c211d5eacdd72d6d79c5543"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "9154d47775ee2323837d7bd0b70ea85ee8bc3da4"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "48e6f1313620f14263d1a179286486a13c5aac20c38aed37aadf22e910a9ca47"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "3f2eb6b59f63f58585c3ebe748895348fedaed2c"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "eb8ced75815c01b7d7c0b337d6e310fa6577e0a508adb813711f48c5cc82e2b9"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
