[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "9adda9a8108bced4deac17ec3804db2195d9a3c3"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "1de54347146027bec3bc0b675e2a42a3d8ba53a7022fbf551e05c449843e19b4"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "baecc896c72d794eca17cad7a9106fa51de99405"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "f10648b83b26417420553b2cb22c4685d33487dafabaccb45c7d4a0bdc59ed6a"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b7f14e7c75ea0318becdffda8f38bb889465d29d"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "00836b929df3ee10d3937ae18c39433c1f150fa7ba0157e06b74706e32198845"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
