[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "39d47c82c8e184ea2504f545771419d8515d8aa6"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "393e1cd91a04c5f4c01ededff440fa9fe8c3fd1b9b5166f1689d3c680b9aa227"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "cdbf22cf33c5b268dd911502c597c1e15008e80c"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "4eaa91f462e1271e54be4d3fc2faadc3252eede4e60ebe0a95f75e66dae254ec"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "8c9f77cc7aae79a2bc6f4e9a0d48c351fafe0fcf"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "516c5bd9bdb0cb7c7afaed8e5c31e71c1389efdfa42b4c7f33c2fadcfc56e170"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
