[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "5d1555e97adcc83614afa2eb9378cb0fdc43c3ca"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "6b4b8406d4b1fe014dff9c749198420f97159677a370f4f5f1eea7d71a679116"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "fa34c8f590aa8cc174cc1ec7d41a27345609b30a"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "26d5e25c4674b071aae46f31f5ae1408027d134a94183ce27742a88581cbbaa4"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c5e322d2fdc170b437b41fc95565b75d3299c747"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "38831ffefd90f9c916cb07c2db5edf1491dd3067d0cb09a17b5820efd290640a"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
