[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "457d3682c86a838430dc02466daeaa7d4283a2b9"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "5449863dca6df75a68c35395fd5ae72d69fb017d1591c36a994375401384d45f"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.1-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.25.1-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "e0e3f0c8a73e1de68e1833221813ec5f06837709"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "c6276418555c1d1cc651941b0677ffc4498c3f66b0d795a7d5ab4b63e643648e"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.1-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.25.1-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1285beb8edaa03ff3dd7463036b53fca58838df0"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "d096fcaf5764ea6a7b8485ef24ae565e5b4f39a17975ff2b89686ec31df654a8"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.1-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.25.1-x86_64-linux-gnu.tar.gz"
