[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "89f47b6236db0ec2b7e2a72aa479743155d5a777"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "3632ba3b59adf86e02decbb4968fe9d110204fb121906e43d19e67eda89352d5"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "9ef1d8464abfc202bc5da6278590aff67ece4eb4"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "29165a0fe6cf4d151b8ac7ed1fcadf9a77a4ecbcb81c46db79b73e182c45ac72"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "6674fd2651fec7c9fbba95d5dcf0b1f034e93c67"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "4687784a8ae7e59b50e541bdd9af295cf5ebcb917761ace624242facc5d16d21"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
