[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "8aff557e88b1028f57bafd388576890655dfd32f"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "9655bea6a93706466a02fb8979ac0478ffd19b43fc1d70e326f591d3b8a7e5d4"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.2-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.25.2-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "ab9a2e5b088c08aeb2a684f3d976b5181162fd79"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "464560d80025cb9db3c8cd2af5c3318879921d63e1587ae967c1ec2e0096dbbf"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.2-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.25.2-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "1285beb8edaa03ff3dd7463036b53fca58838df0"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "68db558daf48e4a22494d981f669e7391e69531027128bac8a88b2475c28cb5e"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.2-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.25.2-x86_64-linux-gnu.tar.gz"
