[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "78f3ce7ab30d7ac82c9d8f30745271e64eb6302b"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "5a984ea6caeabcad20401dd0f2101ff99a4009b5922e14fc2a2d0c2c88484f25"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "84e78dbef04d6ae3e4670256f43d54c52f81ab94"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "cc13e6228bef60f8003f6e5ddff89f7aa7fc0a2cae0e76a501444ffe47d76a51"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "c24eccbc379ae73bcaa2fba5abe59bc0573d6df5"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "2416578cd1604ff583d069e7e9d39240fc4fc54f677e7bbfa0b32896013ab4f6"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
