[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "bebc20df81f1944a9090c459b5cc905f4c810833"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "46138fd4489ca8bec1cb2981ba2217623ecf77d7cd47ec17518b317f67c65970"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "9a24f3e0f1f0440eb05998bd8740baad4467c751"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "2591b567e1d9186419ccc103581c81a5b14b1579921ee7a2aececc42b85aa8df"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "b1f4d0f32c90f7342a27844bd328dff38421a72f"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "34e400403b371a711c1f9a4fb37a61ba4f0194907fd1af8ebfa8a377f08ef80d"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
