[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "fb7fa5fea7194361ae7f9407dbc19fc561feb7b0"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "e830ba1d37b7e2dfe10a3926399da798c74b4c3715abae46bf92cc37403ed9b6"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "5ed98fcf8fcf34bc06cf7e6334820dffb7c1465a"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "9a5a5ecbc15712619d93204fe77c0df07568c9b74ac27f74fee26e1727513512"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "23c3414946cd0deed22359a95f1df9a386815af2"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "ebb736d0c167c57a47399babd9018e651c5cd4c4606c868a358eb36592db5482"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
