[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "28cd22d49fa51f3648330b4dcbab566ab8c2e89e"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "096dca7b699955b36364694f755b3acd79dcf8ec73fe6b71563c61f09b50c6e6"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "753b3db6d3aa3dfd8b340f576182b2d814b7504d"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "5c4bb56eb4d2cb83392b3fbefb193a7204e913518e962ea1b1cebcd956f93f12"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "f49aabc91866b2137e3848ec92de99f224d46030"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "ff4f5c411c0db6bf695e42f4312ec88c29e5905570dd2ad83546447f101774a4"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
