[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "2921be1fb38227e0d75e818ec6cb28efac367df5"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "ddf0ef343f05bd5e30a00275b20a7fda4782172f8fef4b85fb37d5fab1fc3d6b"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "62db0e1e9628fa884009be201161283dce256adb"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "1cd5c102a61cef567171f78134a6e22ef20b9a85fb2d2045160a99e08f4f21a8"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "48fbdf72755818d449f1d373426e2cf0cf93339f"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "ffd9164f5c000c18a0b27c0e33e0cd60ef338f7fce4b2df869ec9bbbb7550efa"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
