[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "b5cfdccfb6976b2452c6048b8ebd065b69e9aeaf"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "d571b90167f70b1eb9e9ede940dd492ef328235aafaacf10ff0b4b319f019439"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "acd59c9829887c358dcccaec82e185160db07af2"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "ee6ccf25e5d75bbd4c4818b785f6826f64726bdad045bdac879e0b48f16d07ef"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e96242ff91f893736b633dfc03faf0be2d31bbda"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "b8bdf7027a7560aef6bd1e26b241f0cfb1bea400f11ca0cef8b26db7d0073f86"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
