[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "486d002ee9c99a31c6c4c88bdd29680530698974"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "c0b584e336641e08da6a273de6e2efb60924af95b124f371f16fa3a4cd412f42"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-v1.25.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "9d39f3278631419313bd5138c3bce4b9ed66cb5c"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "6d21813c1d6bf2d23d52cacf1578ddd5afa57ed0c1ec95339e647d6f0ce5b892"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-build_log-v1.25.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "3b5217963b93fc5ba159e427bb35169ca18777b6"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "804978e07896167279ca3ec1a66d7d2f33ad1d2ce8333d7c2f588c21a5978bb3"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-extract_log-v1.25.0-x86_64-linux-gnu.tar.gz"
