[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "29c5fad8620fcd587779e1902f832549c330e37c"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "3598f186e5c6108930e0d71f0197ced7d6bafc1a0cae6c3793bbfbc608c38bbe"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.12-GCCBoostrap/CrosstoolNG-v1.0.12-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "bfc82c1617e0c53859f8832f4282b8b8afb00de1"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "bd9721e43150a5e7f92dd1a06b6d457b8649838f6ff42ce7745108353bb4102f"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.12-GCCBoostrap/CrosstoolNG-build_log-v1.0.12-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "e3b5f1fd20bf794ac42dc8165431d7c4853ed8af"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "641a0b0db87d9ec8f85317b61200cd9d33b070abb44edea2484e00e2f775cec0"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.12-GCCBoostrap/CrosstoolNG-extract_log-v1.0.12-x86_64-linux-gnu.tar.gz"
