[[CrosstoolNG]]
arch = "x86_64"
git-tree-sha1 = "17d9c0ca78a7c5de3c8895fdd0594447db37a6fe"
libc = "glibc"
os = "linux"

    [[CrosstoolNG.download]]
    sha256 = "b594fe4b64fdef95f2eac69d1c75cb12c8b5b73083552e05bf608e620af1bdd8"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-build_log]]
arch = "x86_64"
git-tree-sha1 = "422d572dea006faff359605fe392622c99122d69"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-build_log.download]]
    sha256 = "818ceafd1590e0af00e00fd7fd0e6c2772239c6d87d101e7e4619363db499555"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-build_log-v1.27.0-x86_64-linux-gnu.tar.gz"

[[CrosstoolNG-extract_log]]
arch = "x86_64"
git-tree-sha1 = "5348b4e2b3ca9d9c2486e26c03368615987b732a"
lazy = true
libc = "glibc"
os = "linux"

    [[CrosstoolNG-extract_log.download]]
    sha256 = "55390b2bf1ba078fa6c797c1e2b6bfb030629800a694955f96133bef164bc730"
    url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.27.0/CrosstoolNG-extract_log-v1.27.0-x86_64-linux-gnu.tar.gz"
