name = "CrosstoolNG"
version = "1.25.0"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "aarch64-linux-gnu"

    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"
    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"
    [[builds.deps]]
    name = "Readline_jll"
    uuid = "05236dd9-4125-5232-aa7c-9ec0c9b2c25a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:6afc9e34904f920817e4778d786a49c785a5620b"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:1b058c9ee5e6c5fc5c0f1a2e680c6c295ce6cda5eb93ed95650a250429ee87fb"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-build_log-v1.25.0-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:74e4f82b3db14d261a0c8ad11184abe4f7520e50"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:60531b37e6dd53f63affc88e1b73fe82e2fdc4bc4eb0c5f4e330e3f0051b117e"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-extract_log-v1.25.0-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbb01ef2e3be60f540f62093e846b21e83ca7401"
    url = "/home/staticfloat/.julia/dev/BinaryBuilder2/bootstrap/CrosstoolNG/bundled"

    [builds.artifact]
    treehash = "sha1:403be1ea9b92b6846e0279902982ab04352bb8a7"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:3f08b0a9d11ec375c3d80d9e217540f63b94915dc6695d57e216e7127000f498"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-v1.25.0-aarch64-linux-gnu.tar.gz"
