name = "CrosstoolNG"
version = "1.0.12"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"
    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:bfc82c1617e0c53859f8832f4282b8b8afb00de1"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:bd9721e43150a5e7f92dd1a06b6d457b8649838f6ff42ce7745108353bb4102f"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.12-GCCBoostrap/CrosstoolNG-build_log-v1.0.12-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:e3b5f1fd20bf794ac42dc8165431d7c4853ed8af"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:641a0b0db87d9ec8f85317b61200cd9d33b070abb44edea2484e00e2f775cec0"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.12-GCCBoostrap/CrosstoolNG-extract_log-v1.0.12-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:b66d485c7922635d450b49674dac396b67f899b4"
    url = "/home/sabae/src/BB2/bootstrap/GCCBootstrap/bundled"

    [builds.artifact]
    treehash = "sha1:29c5fad8620fcd587779e1902f832549c330e37c"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:3598f186e5c6108930e0d71f0197ced7d6bafc1a0cae6c3793bbfbc608c38bbe"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.12-GCCBoostrap/CrosstoolNG-v1.0.12-x86_64-linux-gnu.tar.gz"
