name = "CrosstoolNG"
version = "1.0.14"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"
    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:fa6b2c599b43b61c00ea2e7316d1f40f08f51fb4"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:006732ba6d5205fe39555ccbba103907c947813b2484f8a5b278fe01f3581121"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.14-GCCBoostrap/CrosstoolNG-build_log-v1.0.14-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:c1d9953288d380849c2f5f584b9b7966dd398f47"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:131b1f436dcc8410c85611b2a5f9abbda1cdce36024170d66eacf9a9ba60b2d0"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.14-GCCBoostrap/CrosstoolNG-extract_log-v1.0.14-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:b66d485c7922635d450b49674dac396b67f899b4"
    url = "/home/sabae/src/BB2/bootstrap/GCCBootstrap/bundled"

    [builds.artifact]
    treehash = "sha1:1165ecb9e6072625cbcbc58d27f6d6b0746d9f37"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:b2e06f84bb7d58abe7a26a817691ccabc263fef0e93cb509d47221c258654f8c"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.14-GCCBoostrap/CrosstoolNG-v1.0.14-x86_64-linux-gnu.tar.gz"
