name = "CrosstoolNG"
version = "1.25.4"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "aarch64-linux-gnu"

    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"
    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"
    [[builds.deps]]
    name = "Readline_jll"
    uuid = "05236dd9-4125-5232-aa7c-9ec0c9b2c25a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:ce7fef7051314239b4c2536368989bb01070d48f"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:337407b8e4de487a228dcd5643709ff8e1bf802d24e81a985dfbde694e5d4bd6"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.4-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-build_log-v1.25.4-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:2011f1753f8cc48921623a2f2e952cec6744e7be"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:b69d55fdc925165ec452fd7ce6c3e81f230750964befeec7edcc0c7d8863caf0"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.4-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-extract_log-v1.25.4-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbb01ef2e3be60f540f62093e846b21e83ca7401"
    url = "/home/staticfloat/.julia/dev/BinaryBuilder2/bootstrap/CrosstoolNG/bundled"

    [builds.artifact]
    treehash = "sha1:60d01d35ed35989bb121bda9797d54ec936bbe9a"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:e7392cc4aae128ff90f448b260fadd95d172ff59ca21eb0d7d884a9692252971"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.4-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-v1.25.4-aarch64-linux-gnu.tar.gz"
