name = "CrosstoolNG"
version = "1.0.11"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"
    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:c2f71ba21954868943380dd8c42c829b63ffea9a"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:cab89e510532ceffc0d63411b85f700f00f7f14b1bb4d23077998719845e4f38"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.11-GCCBoostrap/CrosstoolNG-build_log-v1.0.11-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:b874692ee749a3a4f92d553499798907133e8fc1"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:c9674b7b6bec665eda0d5c111943a34cef6c049c9da281eba9406f6aabe364af"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.11-GCCBoostrap/CrosstoolNG-extract_log-v1.0.11-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:b66d485c7922635d450b49674dac396b67f899b4"
    url = "/home/sabae/src/BB2/bootstrap/GCCBootstrap/bundled"

    [builds.artifact]
    treehash = "sha1:6089ecf45ff9e93a0f98078efc3724b8108e506b"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:1cc8d209e59dca8d194e27fd9f2736e01d795216451c49be27f02cc84ffd6469"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.11-GCCBoostrap/CrosstoolNG-v1.0.11-x86_64-linux-gnu.tar.gz"
