name = "CrosstoolNG"
version = "1.25.1"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"
    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:e0e3f0c8a73e1de68e1833221813ec5f06837709"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:c6276418555c1d1cc651941b0677ffc4498c3f66b0d795a7d5ab4b63e643648e"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.1-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.25.1-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:1285beb8edaa03ff3dd7463036b53fca58838df0"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:d096fcaf5764ea6a7b8485ef24ae565e5b4f39a17975ff2b89686ec31df654a8"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.1-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.25.1-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbb01ef2e3be60f540f62093e846b21e83ca7401"
    url = "/home/sabae/src/BB2/bootstrap/CrosstoolNG/bundled"

    [builds.artifact]
    treehash = "sha1:457d3682c86a838430dc02466daeaa7d4283a2b9"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:5449863dca6df75a68c35395fd5ae72d69fb017d1591c36a994375401384d45f"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.1-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.25.1-x86_64-linux-gnu.tar.gz"
