name = "CrosstoolNG"
version = "1.25.2"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"
    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:ab9a2e5b088c08aeb2a684f3d976b5181162fd79"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:464560d80025cb9db3c8cd2af5c3318879921d63e1587ae967c1ec2e0096dbbf"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.2-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.25.2-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:1285beb8edaa03ff3dd7463036b53fca58838df0"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:68db558daf48e4a22494d981f669e7391e69531027128bac8a88b2475c28cb5e"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.2-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.25.2-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbb01ef2e3be60f540f62093e846b21e83ca7401"
    url = "/home/sabae/src/BB2/bootstrap/CrosstoolNG/bundled"

    [builds.artifact]
    treehash = "sha1:8aff557e88b1028f57bafd388576890655dfd32f"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:9655bea6a93706466a02fb8979ac0478ffd19b43fc1d70e326f591d3b8a7e5d4"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.2-GCCBootstrap-x86_64-linux-gnu/CrosstoolNG-v1.25.2-x86_64-linux-gnu.tar.gz"
