name = "CrosstoolNG"
version = "1.25.2"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "aarch64-linux-gnu"

    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"
    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"
    [[builds.deps]]
    name = "Readline_jll"
    uuid = "05236dd9-4125-5232-aa7c-9ec0c9b2c25a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:062544d8b120152df02e860da68ccedcb48fc803"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:20237ca73039347fd452fcd4a119abf20bb46677e19ac228e84d69563b2dc6fe"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.2-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-build_log-v1.25.2-aarch64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:4a246d392405d6d01453cd35d7a20f0ae199ecae"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:535fbcac6f612ef913bd1c21ed0787561bde9a673a8565e1b0756a124133b460"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.2-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-extract_log-v1.25.2-aarch64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbb01ef2e3be60f540f62093e846b21e83ca7401"
    url = "/home/staticfloat/.julia/dev/BinaryBuilder2/bootstrap/CrosstoolNG/bundled"

    [builds.artifact]
    treehash = "sha1:fc15744e9ad603c3a04146e1c96c49c51ce8ca44"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:d70c278fdf8f89cb22d3f9f42d00e62db065788bfb48182282e485eb8106f657"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.2-GCCBootstrap-aarch64-linux-gnu/CrosstoolNG-v1.25.2-aarch64-linux-gnu.tar.gz"
