name = "CrosstoolNG"
version = "1.0.0"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"
    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:2fe7d2a07705f2213d81987a378edef2a306b487"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:9468fab971c278a99d7e955cff137bc07c691475cbf533569bea707593bffe69"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.0-GCCBoostrap-x86_64-linux-gnu/CrosstoolNG-build_log-v1.0.0-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:163a5961cd353e45656f4c7ce457fb3626b49d52"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:73904451909c38307be63b0ea313820710d1402fe84c6a8d64731add37502093"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.0-GCCBoostrap-x86_64-linux-gnu/CrosstoolNG-extract_log-v1.0.0-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:b66d485c7922635d450b49674dac396b67f899b4"
    url = "/home/sabae/src/BB2/bootstrap/GCCBootstrap/bundled"

    [builds.artifact]
    treehash = "sha1:8bd8be23d41a99ec95070c3b21e0d6649859f84a"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:e9fae02371d8f5dff82f997fe906493fd5593f0238cbd29d3a0df898a0efc35a"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.0-GCCBoostrap-x86_64-linux-gnu/CrosstoolNG-v1.0.0-x86_64-linux-gnu.tar.gz"
