name = "CrosstoolNG"
version = "1.25.0"
julia_compat = "1.6"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"
    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:9d39f3278631419313bd5138c3bce4b9ed66cb5c"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:6d21813c1d6bf2d23d52cacf1578ddd5afa57ed0c1ec95339e647d6f0ce5b892"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-build_log-v1.25.0-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:3b5217963b93fc5ba159e427bb35169ca18777b6"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:804978e07896167279ca3ec1a66d7d2f33ad1d2ce8333d7c2f588c21a5978bb3"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-extract_log-v1.25.0-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:bbb01ef2e3be60f540f62093e846b21e83ca7401"
    url = "/home/sabae/src/BB2/bootstrap/CrosstoolNG/bundled"

    [builds.artifact]
    treehash = "sha1:486d002ee9c99a31c6c4c88bdd29680530698974"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:c0b584e336641e08da6a273de6e2efb60924af95b124f371f16fa3a4cd412f42"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.25.0/CrosstoolNG-v1.25.0-x86_64-linux-gnu.tar.gz"
