name = "CrosstoolNG"
version = "1.0.8"
julia_compat = "1.7"
platform_augmentation_code = ""

[[builds]]
name = "CrosstoolNG"
lazy = "false"
src_version = "1.25.0"
platform = "x86_64-linux-gnu"

    [[builds.deps]]
    name = "Ncurses_jll"
    uuid = "68e3532b-a499-55ff-9963-d1c0c0748b3a"
    compat = "*"
    [[builds.deps]]
    name = "Zlib_jll"
    uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
    compat = "*"

    [builds.callback_defs]

    [builds.auxilliary_artifacts.build_log]
    treehash = "sha1:4826e556d15ae5daf368f463c1f027b45fce47d6"

        [[builds.auxilliary_artifacts.build_log.download_sources]]
        tarball_hash = "sha256:87d8c9688ca45fc3b157d0e45e944c10c0ad8ca245a241937213e62b58130f67"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.8-GCCBoostrap/CrosstoolNG-build_log-v1.0.8-x86_64-linux-gnu.tar.gz"

    [builds.auxilliary_artifacts.extract_log]
    treehash = "sha1:29427b7b6dcaacee39f17bfb9055362d0bd3d56b"

        [[builds.auxilliary_artifacts.extract_log.download_sources]]
        tarball_hash = "sha256:95d842e55c01f0a718146bc877d257a96ad701145c2b6f5c035b10efd5039def"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.8-GCCBoostrap/CrosstoolNG-extract_log-v1.0.8-x86_64-linux-gnu.tar.gz"

    [[builds.products]]
    name = "ct_ng"
    type = "executable"
    path = "bin/ct-ng"

    [[builds.sources]]
    treehash = "sha1:2ae4f287410d58c25b345ffbf1978fefd8742f99"
    url = "http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.25.0.tar.xz"
    [[builds.sources]]
    treehash = "sha1:b66d485c7922635d450b49674dac396b67f899b4"
    url = "/home/sabae/src/BB2/bootstrap/GCCBootstrap/bundled"

    [builds.artifact]
    treehash = "sha1:1d0a0d87e3a6744ba527ce89cb1b75f5056f372b"

        [[builds.artifact.download_sources]]
        tarball_hash = "sha256:036f12286a2ce2be6b1a1b60b7033efa0dec93a033bb9a68725695587de48ca0"
        url = "https://github.com/staticfloat/CrosstoolNG_jll.jl/releases/download/v1.0.8-GCCBoostrap/CrosstoolNG-v1.0.8-x86_64-linux-gnu.tar.gz"
